current.db=pg

# MS SQL Server
mssql.url=jdbc:sqlserver://localhost:1433;databaseName=ParkingDB;encrypt=false;trustServerCertificate=true;
mssql.user=sa
mssql.password=123

# PostgreSQL
pg.url=jdbc:postgresql://3e24e-rw.db.pub.dbaas.postgrespro.ru:5432/dbstud
pg.user=obuhova_ss
pg.password=L0qReeOB#W81